# Generated by Django 5.0.6 on 2024-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_pswd",
            field=models.CharField(default="", max_length=255),
        ),
    ]
