# Generated by Django 5.0.6 on 2024-06-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_contact_contact_pswd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_email", models.EmailField(max_length=255)),
                ("login_password", models.CharField(max_length=255)),
            ],
        ),
    ]
