# Generated by Django 5.0.6 on 2024-06-05 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_login"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
