# Generated by Django 5.0.6 on 2024-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_delete_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_name", models.CharField(max_length=255)),
                ("registration_phn", models.CharField(max_length=255)),
                ("registration_email", models.EmailField(max_length=255)),
                ("registration_paswrd", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
