# Generated by Django 5.0.6 on 2024-06-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
            ],
        ),
    ]
