# Generated by Django 5.0.6 on 2024-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.FileField(null=True, upload_to="products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_price",
            field=models.FloatField(),
        ),
    ]
