# Generated by Django 5.0.6 on 2024-06-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_user", models.CharField(default=None, max_length=250)),
                ("order_name", models.CharField(max_length=250)),
                ("order_price", models.FloatField(max_length=250)),
                (
                    "order_image",
                    models.FileField(max_length=255, null=True, upload_to=""),
                ),
                ("order_qty", models.IntegerField()),
                ("order_amount", models.FloatField()),
                ("order_address", models.TextField(max_length=255, null=True)),
                ("order_dlvtyp", models.CharField(max_length=255, null=True)),
                ("order_status", models.IntegerField(default=0)),
            ],
        ),
    ]
